# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publish:
          context: semantic_release
          requires:
            - test
          filters:
            branches:
               only: v2



imageA: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:lts
  environment:
    NODE_ENV: test

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm ci
      - run:
          name: Run ESLint and Typescript CLI
          command: npm run lint && npm run build
      - run:
          name: Run unit tests
          command: npm test
      - run:
          name: Run e2e tests
          command: npm run test:cov
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/tmp
          paths: .
  publish:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/tmp
      - run:
          name: Build and Publish Docker
          command: npm run semantic-release
